default_platform(:android)

platform :android do

  desc "Deploy to Google Play Store (production track)"
  lane :deploy do
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "production",
      release_status: "completed",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy to Google Play Store (internal testing)"
  lane :internal do
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "internal",
      release_status: "completed",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

end
